services:
  backend:
    build: .
    container_name: refurb_backend
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: refurb_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  frontend:
    build:
      context: ../refurblab-dashboard
      dockerfile: Dockerfile
    container_name: refurblab_dashboard
    env_file:
      - .env     # if you have frontend-specific env vars
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:
